name: Publish Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - 'debug/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Run build script
      run: sh ./.vscode/build.sh
      # run: pnpm run build

    - name: Upload Release Assets
      uses: actions/upload-artifact@v4
      with:
        name: Artifact-${{ matrix.runs-on }}
        path: ./out

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: Artifact-*
        path: ./out
        merge-multiple: true

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        overwrite: true
        release_name: Release
        file: ./out/decky-rifm.zip
        asset_name: decky-rifm.zip
        tag: latest